version: '3.5'

services:
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
  backend:
    image: example-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=database
    ports:
      - 8080:8080
  redis:
    image: redis
    restart: unless-stopped
  database:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres